require newer yarn
solves errors like:

error "ajv" is wrong version: expected "4.11.2", got "5.2.0"
error "webpack#ajv" not installed
error Found 2 errors.
Error: You have unmet dependencies. (`yarn check` command failed)
Run `yarn install` to install missing modules.

exact version which fixes is not known